name: 💬 Discussion
description: Start an open discussion
title: "[DISCUSSION] "
labels: ["discussion"]
body:
  - type: textarea
    id: topic
    attributes:
      label: Topic
      placeholder: What do you want to discuss?
    validations:
      required: true